export const portfolioProjects = [
  {
    title: "Project Monaco - Monaco",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio1-image-1.jpg",
      "/fwdportfolio1-image-2.jpg",
      "/fwdportfolio1-image-3.jpg",
      "/fwdportfolio1-image-4.jpg",
      "/fwdportfolio1-image-5.jpg",
      "/fwdportfolio1-image-6.jpg",
      "/fwdportfolio1-image-7.jpg",
      "/fwdportfolio1-image-8.jpg",
    ],
  },
  {
    title: "Project Paris - France  Hampstead - London",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio2-image-01.jpg",
      "/fwdportfolio2-image-02.jpg",
      "/fwdportfolio2-image-03.jpg",
      "/fwdportfolio2-image-04.jpg",
      "/fwdportfolio2-image-05.jpg",
      "/fwdportfolio2-image-06.jpg",
      "/fwdportfolio2-image-07.jpg",
      "/fwdportfolio2-image-08.jpg",
      "/fwdportfolio2-image-09.jpg",
      "/fwdportfolio2-image-10.jpg",
      "/fwdportfolio2-image-11.jpg",
      "/fwdportfolio2-image-12.jpg",
      "/fwdportfolio2-image-13.jpg",
      "/fwdportfolio2-image-14.jpg",
      "/fwdportfolio2-image-15.jpg",
      "/fwdportfolio2-image-16.jpg",
    ],
  },
  {
    title: "Project Dury - london",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio3-image-01.jpg",
      "/fwdportfolio3-image-02.jpg",
      "/fwdportfolio3-image-03.jpg",
      "/fwdportfolio3-image-04.jpg",
      "/fwdportfolio3-image-05.jpg",
      "/fwdportfolio3-image-06.jpg",
      "/fwdportfolio3-image-07.jpg",
      "/fwdportfolio3-image-08.jpg",
      "/fwdportfolio3-image-09.jpg",
      "/fwdportfolio3-image-10.jpg",
      "/fwdportfolio3-image-11.jpg",
      "/fwdportfolio3-image-12.jpg",
      "/fwdportfolio3-image-13.jpg",
      "/fwdportfolio3-image-14.jpg",
      "/fwdportfolio3-image-15.jpg",
    ],
  },
  {
    title: "Project Polo - Dubai",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio4-image-001.jpg",
      "/fwdportfolio4-image-002.jpg",
      "/fwdportfolio4-image-003.jpg",
      "/fwdportfolio4-image-004.jpg",
      "/fwdportfolio4-image-005.jpg",
      "/fwdportfolio4-image-006.jpg",
      "/fwdportfolio4-image-007.jpg",
      "/fwdportfolio4-image-008.jpg",
      "/fwdportfolio4-image-009.jpg",
      "/fwdportfolio4-image-010.jpg",
      "/fwdportfolio4-image-011.jpg",
      "/fwdportfolio4-image-012.jpg",
      "/fwdportfolio4-image-013.jpg",
      "/fwdportfolio4-image-014.jpg",
      "/fwdportfolio4-image-015.jpg",
    ],
  },
  {
    title: "Project Wrotham - London",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio5-image-1.jpg",
      "/fwdportfolio5-image-2.jpg",
      "/fwdportfolio5-image-3.jpg",
      "/fwdportfolio5-image-4.jpg",
      "/fwdportfolio5-image-5.jpg",
      "/fwdportfolio5-image-6.jpg",
      "/fwdportfolio5-image-7.jpg",
      "/fwdportfolio5-image-8.jpg",
    ],
  },
  {
    title: "Project Montevetro - London",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio6-image-1.jpg",
      "/fwdportfolio6-image-2.jpg",
      "/fwdportfolio6-image-3.jpg",
      "/fwdportfolio6-image-4.jpg",
      "/fwdportfolio6-image-5.jpg",
      "/fwdportfolio6-image-6.jpg",
      "/fwdportfolio6-image-7.jpg",
    ],
  },
  {
    title: "Project Camlet - London",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio7-image-1.jpg",
      "/fwdportfolio7-image-2.jpg",
      "/fwdportfolio7-image-3.jpg",
      "/fwdportfolio7-image-4.jpg",
      "/fwdportfolio7-image-5.jpg",
      "/fwdportfolio7-image-6.jpg",
      "/fwdportfolio7-image-7.jpg",
      "/fwdportfolio7-image-8.jpg",
      "/fwdportfolio7-image-9.jpg",
      "/fwdportfolio7-image-10.jpg",
      "/fwdportfolio7-image-11.jpg",
      "/fwdportfolio7-image-12.jpg",
    ],
  },
  {
    title: "Project Ebury - London",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio8-image-1.jpg",
      "/fwdportfolio8-image-2.jpg",
      "/fwdportfolio8-image-3.jpg",
      "/fwdportfolio8-image-4.jpg",
      "/fwdportfolio8-image-5.jpg",
      "/fwdportfolio8-image-6.jpg",
      "/fwdportfolio8-image-7.jpg",
      "/fwdportfolio8-image-8.jpg",
    ],
  },
  {
    title: "Project Al Barari 1 - Dubai",
    publishedAt: "18.08.2025",
    images: [
      "/fwdportfolio9-image-1.jpg",
      "/fwdportfolio9-image-2.jpg",
      "/fwdportfolio9-image-3.jpg",
      "/fwdportfolio9-image-4.jpg",
      "/fwdportfolio9-image-5.jpg",
      "/fwdportfolio9-image-6.jpg",
      "/fwdportfolio9-image-7.jpg",
      "/fwdportfolio9-image-8.jpg",
    ],
  },
  {
    title: "Project Al Barari 2 - Dubai",
    publishedAt: "18.02.2025",
    images: [
      "/fwdportfolio10-image-1.jpg",
      "/fwdportfolio10-image-2.jpg",
      "/fwdportfolio10-image-3.jpg",
      "/fwdportfolio10-image-4.jpg",
      "/fwdportfolio10-image-5.jpg",
      "/fwdportfolio10-image-6.jpg",
      "/fwdportfolio10-image-7.jpg",
      "/fwdportfolio10-image-8.jpg",
    ],
  },
  {
    title: "Marine Portfolio",
    publishedAt: "13.03.2026",
    images: [
      "/fwdportfolio11-image-1.jpeg",
      "/fwdportfolio11-image-2.jpeg",
      "/fwdportfolio11-image-3.jpeg",
      "/fwdportfolio11-image-4.jpeg",
      "/fwdportfolio11-image-5.jpeg",
      "/fwdportfolio11-image-6.jpeg",
      "/fwdportfolio11-image-7.jpeg",
      "/fwdportfolio11-image-8.jpeg",
    ],
  },
  {
    title: "Aviation Portfolio",
    publishedAt: "14.03.2026",
    images: ["/fwdportfolio12-image-1.jpeg", "/fwdportfolio12-image-2.jpeg", "/fwdportfolio12-image-3.jpeg", "/fwdportfolio12-image-4.jpeg"],
  },
];
